version: '3'

services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory
    ports:
      - 5434:5432

  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: inventory_web
    container_name: inventory_container
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  db_data: