# Generated by Django 4.2.3 on 2023-12-02 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 14, 54, 29, 678893)),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 2, 14, 54, 29, 679597)),
        ),
    ]
