# Generated by Django 4.2.3 on 2023-11-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='margin_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
