# Generated by Django 4.2.3 on 2023-11-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('sale', 'sale'), ('purchase', 'purchase')], default='admin', max_length=100, null=True),
        ),
    ]
